### ISSUE TITLE
Preview plug-in issues

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#19]
The Preview works intermittently on some content. To reproduce:

1. Clone this repo: https://github.com/AdobeDocs/target.en
2. Test by selecting Preview on several documents.

In some cases, the Preview window is blank. In some cases, the same article that previews properly in one session fails to preview in a different session. We've tested this Target content on 2 different machines and confirmed it's an issue. 

@geverit4

**Comment by geverit4** [comment]
We cannot reproduce this bug.  Can you add more specific steps of a click sequence that causes the problem?  

How we tested:
- Follow the instructions above to clone the target.en repository
- Selected preview on several documents.  Each showed up fine in the preview pane, and it is even possible to switch among active documents without losing the preview functionality.

**Comment by bbringhu** [comment]
@geverit4 - If it's OK with you, I'll set up a meeting next week so I can show you what I'm seeing. And perhaps we can go over the list of outstanding issues.

**Comment by geverit4** [comment]
I've accepted the meeting invite for next week.  Can you also add @aaronlugo to the meeting invitation?

**Comment by bbringhu** [comment]
I included @aaronlugo in the invite.

**Comment by geverit4** [comment]
It looks like we found a passable workaround for this issue:  Use the "Change Preview Security Settings" option on the preview panel in VSC. 
![1b01b44d-8dc2-40b6-81ed-e88277e1c509](https://user-images.githubusercontent.com/1187616/142503360-dcd015e9-4070-4e3e-99de-9504c3353ce8.png)
![9e2afa45-5532-4d52-9c13-7838740140a9](https://user-images.githubusercontent.com/1187616/142503388-7297481c-d524-4e4a-bbdb-06f8959c5be2.jpg)

And select one of the more permissive security options: 

- Allow Insecure Local Content
- Allow insecure Content
- Disable

**Comment by geverit4** [comment]
May be fixed with update.  Revisit with next release.

**Comment by geverit4** [comment]
@bbringhu can we close this issue?

**Comment by bbringhu** [comment]
@mtalbot29 - Is this still an issue with the latest extension?

**Comment by bbringhu** [comment]
Closing this issue until we can reproduce again.
