### ISSUE TITLE
Update plugin to leverage new validation rules

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#21]
@geverit4 - Please work with Jorge to update the plugin validation rules to use the latest updates. When you're ready to sync, ping me, and I'll make a list of the latest rules available, as we've done in the past.

**Comment by geverit4** [comment]
@bbringhu is Jorge enabled on this repo?  I can't find his username to @ reference.  I seem to remember it was something that did not have his name in it.  @aaronlugo is on it.

**Comment by bbringhu** [comment]
@geverit4 - Jorge is @end58763

**Comment by geverit4** [comment]
Issue resolved.
