### ISSUE TITLE
Only 3 Heading levels?

### ISSUE THREAD

**Issue by jeffchasin** [AdobeDocs/vsc-extensions#25]
The [exposed commands](https://marketplace.visualstudio.com/items?itemName=AdobeExL.adobe-markdown-authoring#:~:text=md%2Dshortcut.toggleTitleH1,Toggle%20%23%23%23%23%23%23%20H6%20title) of the extension list Heading levels 1-6, but the Authoring Guide says [only levels 1-3](https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#:~:text=We%20recommend%20only%203%20heading%20levels.%20Levels%204%20and%20beyond%20are%20not%20rendering%20properly%20at%20this%20time.) are rendering correctly - not sure which is right? Can we use 1-6?
>

**Comment by bbringhu** [comment]
@jeffchasin - Only levels 1-3 are rendered with formatting, but there's nothing preventing you from using headings 4-6 if you have a reason. Headings 4-6 are rendered with body text formatting by default.
