### ISSUE TITLE
Exclude {style=table} formatting from preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#26]
To render markdown tables using a different engine, we add `{style="table-layout:fixed"}` or `{style="table-layout:auto"}` on its own line below a markdown table. Please don't show this syntax in preview.

**Comment by bbringhu** [comment]
@geverit4 - Yes, that is representative except for 2 things:

* We require table rows to have open and close pipe characters ( | )
* We require a blank line between the table and the {style} syntax

Example:

| Action |Planner |Worker |Reviewer |Requestor |External user |
|---|---|---|---|---|---|
| Create |✓&#42; |✓&#42; |&nbsp; |&nbsp; |&nbsp; |
| Delete |✓&#42; |✓&#42; |&nbsp; |&nbsp; |&nbsp; |
| Log hours |✓ |✓ |&nbsp; |&nbsp; |&nbsp; |
| Accept an assignment |✓ |✓ |&nbsp; |&nbsp; |&nbsp; |
| Make an assignment |✓ |✓ |^only in in-line edit |^only in in-line edit |&nbsp; |
| Attach a custom form |✓ |✓ |&nbsp; |&nbsp; |&nbsp; |
| View finance |✓ |✓ |✓ |&nbsp; |&nbsp; |
| Updates/comments |✓ |✓ |✓ |&nbsp; |&nbsp; |

{style="table-layout:auto"}

**Comment by geverit4** [comment]
This was addressed in the Markdown-it-adobe-plugin.
