### ISSUE TITLE
Change the MD033 validation check about HTML

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#27]
When checking validation, we flag certain HTML tags as invalid even if it's supported. For example, we flag `<a href>` links as errors. We have an allow list of HTML syntax. The following HTML tags are allowed and should not be flagged as errors:

`<table>`
`<tbody>`
`<td>`
`<tfoot>`
`<thead>`
`<th>`
`<tr>`
`<col>`
`<colgroup>`
`<p>`
`<ul>` (unordered list / numbered list)
`<ol>` (ordered list / bullet list)
`<li>` (list item)
`<br>` (line break)
`<b>`
`<caption>`
`<I>`
`<strong>` (bold)
`<u>` (underline)
`<s>` (strikethrough)
`<span>`
`<sub>` (subscript)
`<sup>` (superscript)
`<a>`
`<img>`
`<div>`
`<em>` (emphasis, italics)
`<pre>` (codeblock)
`<code>
`<codeblock>`

**Comment by geverit4** [comment]
Phase 1: turn off MD033 by default in the package.json
Phase 2: create a new MD message that only allows HTML from the include list above.

**Comment by geverit4** [comment]
Revamped the user settings override.  If the user already has rules for Markdown, it will leave them alone and only merge in new items from the package.json configuration file.   

Updated the README:

## Markdown Lint Validation Settings

This package uses David Anson's Markdown-Lint package to validate the markdown.  In addition to the built-in validation
rules, this package adds support for Adobe Flavored Markdown.  

### Changing the Markdown-Lint Validation Settings

When it starts up for the first time the Adobe Markdown Authoring extension will look for existing settings in the 
VSCode Settings.  If it does not find them, it will add the default settings below.  If it does find them, it will
default to the values found in the user settings.

To change the settings, go to Preferences > Settings > markdownlint.

```
markdownlint.config: {
    "line-length": false,
    "AM001": false,
    "AM009": false,
    "AM011": false,
    "MD003": {
      "style": "atx"
    },
    "MD004": {
      "style": "dash"
    },
    "MD007": {
      "indent": 4
    },
    "MD009": false,
    "MD012": false,
    "MD014": false,
    "MD024": false,
    "MD025": {
      "front_matter_title": ""
    },
    "MD026": false,
    "MD027": false,
    "MD028": false,
    "MD030": {
      "ul_multi": 3,
      "ol_multi": 2
    },
    "MD033": {
      "allowed_elements": [
        "a",
        "b",
        "br",
        "caption",
        "code",
        "col",
        "colgroup",
        "div",
        "em",
        "I",
        "img",
        "li",
        "ol",
        "p",
        "pre",
        "s",
        "span",
        "strong",
        "sub",
        "sup",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "tr",
        "u",
        "ul"
      ]
    },
    "MD036": false,
    "MD038": false,
    "MD039": false,
    "MD040": false,
    "MD045": false
  }
```
### Custom Rules

In addition to the standard support MD### rules, Adobe Markdown Extension supports AM### rules, which are specific to 
Adobe Flavored Markdown.

```
  "markdownlint.customRules": [
    "{adobeexl.adobe-markdown-authoring}/markdownlint-custom-rules/rules.js"
  ]
```

**Comment by geverit4** [comment]
Issue resolved.
