### ISSUE TITLE
Support collapsible sections in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#28]
https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#collapsible-sections

```
+++Click me
This is text inside a collapsible section.

* Bullet one
* Bullet two
* Bullet three

+++
```

**Comment by geverit4** [comment]
Added support in markdow-it-adobe-plugin@1.1.5.

![Screenshot 2022-07-27 at 11 13 32 PM](https://user-images.githubusercontent.com/1187616/181412539-a9368ea4-4118-4b9a-98f4-6b6148b1bf06.png)
![Screenshot 2022-07-27 at 11 13 42 PM](https://user-images.githubusercontent.com/1187616/181412547-189805bd-90da-4f40-bcc2-ecc003df94e9.png)

**Comment by geverit4** [comment]
Issue resolved.
