### ISSUE TITLE
Enable snippets and includes in preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#29]
See slide deck sent via email 2022-06-13.

Additional info:

https://experienceleague.adobe.com/docs/authoring-guide-exl/using/authoring/features/includes.html

**Comment by geverit4** [comment]
Uploaded PPT file for convenience.
[snippets.pdf](https://github.com/AdobeDocs/vsc-extensions/files/9123252/snippets.pdf)

**Comment by geverit4** [comment]
Issue resolved.
