### ISSUE TITLE
Edit smart characters

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#30]
Can we include these in the AdobeDocs VSCode Plugin?
  
docs-markdown
In settings.json, you can set “Replace smart quotes”  and this will automatically replace them.
 
Highlight Bad Chars
With this config:
    "highlight-bad-chars.additionalUnicodeChars": [
       
        "\u200E",
        "\u200F",
        "\u0009",
        "\u2018",
        "\u2019",
        "\u201C",
        "\u201D"
    ],
 
There might be other bad chars, but these were some of the “Smart” chars we saw.

**Comment by geverit4** [comment]
Absolutely.  No problem.

**Comment by geverit4** [comment]
Before editing the example paragraph:

![Screen Shot 2022-07-26 at 9 04 43 PM](https://user-images.githubusercontent.com/1187616/181138372-7ca13f6c-89e9-4079-b4be-cbfaa31e102b.png)

After cutting and pasting the paragraph:

![Screen Shot 2022-07-26 at 9 05 10 PM](https://user-images.githubusercontent.com/1187616/181138402-a721b8d4-901c-4695-8be4-dc6329afde95.png)

**Comment by geverit4** [comment]
Issue resolved.
